In [38]:
import numpy as np

In [39]:
v1 = np.array([10,20,5])
v2 = np.array([5,5,10])
print(v2)
print(v1*v2)
print(v1.dot(v2))

[ 5  5 10]
[ 50 100  50]
200


In [40]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m1)
print("\n","="*8,"\n")
m2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m2)
print("\n","="*8,"\n")
print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


property method..see

In [41]:
class Student:
    
    def __init__(self,name):
        self.name = name 
        
    @property #call without parenthesis
    def fname(arg):
        # return f"{name}"
        pass
# take obj and call method without ()

In [42]:
print(v1.ndim)
print(v1.shape) #column vector

1
(3,)


In [43]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
vec = np.array([1,2,3,4])
print(vec.shape)
print(vec.shape[0])
# print(vec.shape[1])#wrong because this is vector not matrix
mat = vec.reshape(vec.shape[0],1)
print(mat)
print("\n","="*8,"\n")

mat=vec[:,None]
print(mat)

(4,)
4
[[1]
 [2]
 [3]
 [4]]


[[1]
 [2]
 [3]
 [4]]


In [45]:
mat=np.array([["1",2,3],
               [4,5,6],
               [7,8,9]])
mat.dtype
# uniform string 11...u11 is type
# obj..str..float..int...bool (with ordered data type)priority

dtype('<U21')

In [46]:
class C:
    pass
o1=C()
mat=np.array([["1",o1,3],
               [4,5,6],
               [7,8,9]])
mat.dtype

dtype('O')

In [47]:
mat=np.array([["1",2,3],
               [4,5,6],
               [7,8,9]])
mat

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [ ]:
mat=np.array([["1",2,3],
               [4,5,6],
               [7,8,9]])
f_mat=mat.astype(float)
print(f_mat.dtype)
f_mat

<U21


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])