# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [14]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    # TODO: Students implement logic here
    pass

In [15]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.

    :param mode: A string indicating the type of array to create ('zeros', 'ones', 'full', 'identity').
    :type mode: str
    :param shape: A tuple indicating the shape of the array to create.
    :type shape: tuple
    :param value: A value to fill the array with (only used for 'full' mode).
    :type value: any, optional

    :return: A NumPy array of the specified type and shape.
    :rtype: np.ndarray
    """

    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        if value is None:
            raise ValueError("Value must be provided for 'full' mode.")
        return np.full(shape, value)
    elif mode == 'identity':
        if shape[0] != shape[1]:
            raise ValueError("Shape must be square for 'identity' mode.")
        return np.eye(shape[0])
    else:
        raise ValueError("Invalid mode. Choose from 'zeros', 'ones', 'full', or 'identity'.")

print(array_factory('zeros', (2, 3)))
print(array_factory('ones', (2, 3)))
print(array_factory('full', (2, 3), value=7))
print(array_factory('identity', (4, 4)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [16]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.

    :param data1: First dataset to be reshaped and stacked.
    :type data1: array-like
    :param data2: Second dataset to be stacked with the first.
    :type data2: array-like
    :param new_shape: The new shape to which the first dataset should be reshaped.
    :type new_shape: tuple  

    :return: A vertically stacked matrix of the reshaped first dataset and the second dataset.
    :rtype: np.ndarray
    """
    try:

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = np.reshape(arr1, new_shape)

        if reshaped_arr1.shape[1] != arr2.shape[1]:
            raise ValueError("Both matrices must have the same number of columns.")
        combined_dataset = np.vstack([reshaped_arr1, arr2])

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [17]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.

    :param arr: Input array to be modified.
    :type arr: array-like
    :param threshold: The threshold value for comparison.
    :type threshold: numeric
    :param replacement_value: The value to replace elements that meet the condition (default is -1).
    :type replacement_value: numeric, optional  

    :return: A modified array where elements >= threshold are replaced with replacement_value.      
    :rtype: np.ndarray
    """
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

TestCase

In [18]:

branch_a = [1, 2, 3, 4, 5, 6] 
branch_b = [[7, 8, 9], 
            [10, 11, 12]]
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])